### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by danielzzz** [scherersoftware/cake-bootstrap3#1]
hi, would you please add some documentation on how to use/activate this plugin and basic info what it contains?

thanks, best, dan

**Comment by robertscherer** [comment]
Hi,

it contains bake Templates and we used to use it to make the FormHelper Bootstrap-Aware. Since then, there are better FormHelper Plugins out there, I'd recommend https://github.com/Holt59/cakephp3-bootstrap3-helpers for that.

Once we have the Bake Templates production-ready, we'll surely update the readme.

Cheers,
Robert

**Comment by danielzzz** [comment]
ok, thx
